### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by daslicht** [pbastowski/body-parser#1]
Hello,
how to access uploaded files please?

body is anytime undefined here?

**Comment by pbastowski** [comment]
Have a look at this example for file uploads: https://github.com/pbastowski/meteor-upload-files. 

Body-parser is not meant for receiving files. See it's README.md.

**Comment by daslicht** [comment]
I found that out as well by now :)
and I used busboy now.

Now I am stuck at writing the data into gridfs :/
